# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class login_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(527, 449)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(220, 300, 241, 61))
        self.login.setStyleSheet("QPushButton{\n"
                                 "    color:White;\n"
                                 "    border-radius: 12px;\n"
                                 "    font-family:微软雅黑;\n"
                                 "    background:#6633FF;\n"
                                 "    border:2px;\n"
                                 "    font:18pt;\n"
                                 "}\n"
                                 "QPushButton:hover{\n"
                                 "    background:#6666FF;\n"
                                 "}\n"
                                 "QPushButton:pressed{\n"
                                 "    background:#6600FF;\n"
                                 "}")
        self.login.setObjectName("login")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 110, 141, 51))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("QLabel{\n"
                                 "    color:White;\n"
                                 "    border-radius: 12px;\n"
                                 "    font-family:微软雅黑;\n"
                                 "    background:#73262F;\n"
                                 "    border:2px;\n"
                                 "    font:18pt;\n"
                                 "}\n"
                                 "")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 141, 51))
        self.label_2.setStyleSheet("QLabel{\n"
                                   "    color:White;\n"
                                   "    border-radius: 12px;\n"
                                   "    font-family:微软雅黑;\n"
                                   "    background:#73262F;\n"
                                   "    border:2px;\n"
                                   "    font:18pt;\n"
                                   "}\n"
                                   "")
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(220, 110, 241, 51))
        self.username.setStyleSheet("QLineEdit{\n"
                                    "    color:White;\n"
                                    "    border-radius: 18px;\n"
                                    "    font-family:微软雅黑;\n"
                                    "    background:#825ee2;\n"
                                    "    border:4px;\n"
                                    "    font:16pt;\n"
                                    "}")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(220, 210, 241, 51))
        self.password.setStyleSheet("QLineEdit{\n"
                                    "    color:White;\n"
                                    "    border-radius: 18px;\n"
                                    "    font-family:微软雅黑;\n"
                                    "    background:#855ee2;\n"
                                    "    border:4px;\n"
                                    "    font:16pt;\n"
                                    "}")
        self.password.setObjectName("password")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 531, 451))
        self.label_3.setStyleSheet("border-image:url(login_background.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.login.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.username.raise_()
        self.password.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setText(_translate("MainWindow", "登录"))
        self.label.setText(_translate("MainWindow", "用户名"))
        self.label_2.setText(_translate("MainWindow", "密码"))
